name: Release gut_cert_check

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  gut-plugin-release:
    uses: gut-hub/workflows/.github/workflows/gut-plugin-release.yml@main
    with:
      plugin-name: gut_cert_check
