name: Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-binary
        path: target/release/libgut_cert_check.so

  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release

    - name: Upload MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-binary
        path: target/release/libgut_cert_check.dylib

  release_all:
    runs-on: ubuntu-latest
    needs: [build_linux, build_macos]

    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: linux-binary
    - name: Download MacOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: macos-binary

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
            libgut_cert_check.so
            libgut_cert_check.dylib
